"""decouple storage provider from library

Revision ID: d82a4ded26ba
Revises: e8b4d2f91a3c
Create Date: 2026-08-13 20:39:25.211404

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd82a4ded26ba'
down_revision: Union[str, None] = 'e8b4d2f91a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE movies, collections CASCADE")
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_libraries_storage_provider_id_storage_providers'), type_='foreignkey')
        batch_op.drop_column('storage_provider_id')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_provider_id', sa.UUID(), nullable=False))
        batch_op.create_index(batch_op.f('ix_movies_storage_provider_id'), ['storage_provider_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_movies_storage_provider_id_storage_providers'), 'storage_providers', ['storage_provider_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE movies, collections CASCADE")
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movies_storage_provider_id_storage_providers'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_movies_storage_provider_id'))
        batch_op.drop_column('storage_provider_id')

    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_provider_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_libraries_storage_provider_id_storage_providers'), 'storage_providers', ['storage_provider_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###
